### ISSUE TITLE
CustomHeads Fehler bei setzen.

### ISSUE THREAD

**Issue by ExticDev** [EinBexiii/CustomHeads#3]
Moin, wollte mal fragen warum immer mein ganzen Spieler austimmen wenn sie einen Kopf setzten?

**Comment by EinBexiii** [comment]
Das Plugin wird bald ein rewrite bekommen, warum das passiert kann ich dir noch nicht beantworten.

**Comment by ExticDev** [comment]
Wann in etwa?

**Comment by EinBexiii** [comment]
Wenn ich Zeit habe, eventuell morgen.

**Comment by Creeperface01** [comment]
@EinBexiii what is nukkit bug? Does the crash occur even if you don't send the skin packet?

**Comment by EinBexiii** [comment]
@Creeperface01 If I don't send the skin packet, nothing crashes.

**Comment by EinBexiii** [comment]
fixed in #7
