### ISSUE TITLE
REWRITE AND UPDATE

### ISSUE THREAD

**Issue by EinBexiii** [EinBexiii/CustomHeads#4]
The plugin will get a rewrite. Also new features will be added.

**Comment by Daniel-Ric** [comment]
Soon?

**Comment by EinBexiii** [comment]
Until the crash bug is fixed, I'm not gonna do anything here. ( Nukkit BUG )

**Comment by Daniel-Ric** [comment]
which one?

**Comment by EinBexiii** [comment]
#3
