### ISSUE TITLE
Spieler Timen Aus 

### ISSUE THREAD

**Issue by Hajatoby** [EinBexiii/CustomHeads#6]
Hey,  
Geiles Plugin und Geile Funktion, 
Leider musste ich jedoch Feststellen, dass Alle Spieler Austimen sobald ein Kopf Plaziert wird. 
Wäre es möglich dies Zeitnah zu beheben? Von mir aus auch Entgeldlich? 

Falls ja Schreib mir gerne bei Discord Hajatoby#0001 
oder Hier

LG

**Comment by EinBexiii** [comment]
#3 duplicate. Ich werde es beheben sobald ich Zeit habe. Ich Arbeite momentan an großen Privaten Projekten und die nehmen halt Zeit. Ich werde mir morgen wahrscheinlich die Zeit nehmen um eine Lösung für dieses Problem zu finden.
