### ISSUE TITLE
Warum kann jeder jeden Kopf abbauen?

### ISSUE THREAD

**Issue by ExticDev** [EinBexiii/CustomHeads#8]
Woran liegt das, das jeder jeden Kopf abbauen kann von jedem User?

**Comment by EinBexiii** [comment]
Das liegt daran, dass ich keine Permissions hinzugefügt habe. Jedoch existieren eigene Events, mit denen man das verhindern kann. Ich werde mich morgen hinsetzen und das Plugin etwas überarbeiten.
