### ISSUE TITLE
Warum kann jeder jeden Kopf abbauen?

### ISSUE THREAD

**Issue by ExticDev** [EinBexiii/CustomHeads#9]
Bitte fix den Bug! Jeder kann jeden Kopf abbauen. Jeder User.

**Comment by EinBexiii** [comment]
Erstell bitte keine unnötigen issues, zu mal das kein Bug ist.

**Comment by ExticDev** [comment]
klar, aber wie soll ich das dann beheben ist doch scheiße wenn user jeden kopf abbauen können lol

**Comment by EinBexiii** [comment]
Hab ich mich bei der ersten issue von dir nicht deutlich ausgedrückt?
